### ISSUE TITLE
The mixin version does not define this.styles

### ISSUE THREAD

**Issue by jason-wolfe** [casesandberg/reactcss#10]
Documentation makes it seem like you should be able to call this.styles() no matter what version you're using, but when you do that with the "inline" version, this.styles is undefined and this.css must be used instead.

**Comment by casesandberg** [comment]
Hey @jason-wolfe, sorry for the confusion. I am going to be splitting out the documentation so there is a section for both the mixins implementation and the es5 implementation. 

In the meantime, you can check out a working file of it here: https://github.com/casesandberg/reactcss/blob/master/examples/Button.es5.jsx#L49

Notice on like 49, you have to declare a `styles` function that returns `this.css`, that's what makes it work.

**Comment by casesandberg** [comment]
Added calling the styles function to the mixins example!

**Comment by jason-wolfe** [comment]
Thanks!
