### ISSUE TITLE
Documentation confuses styles and style

### ISSUE THREAD

**Issue by jason-wolfe** [casesandberg/reactcss#11]
Example from documentation: ```<div styles={ this.styles().modal }>```. The actual property on the DOM elements is style, not styles.

**Comment by casesandberg** [comment]
See the answer on https://github.com/casesandberg/reactcss/issues/10, when using the mixin implementation you have to define this.styles yourself. I wanted to have it auto-included by the mixin, but react yells at you when you try to overwrite it, and you need to be able to overwrite it when you activate classes with custom expressions.

**Comment by jason-wolfe** [comment]
Hmm I'm not sure if you're misreading or if I'm confused on this one. I was referring to the prop name on div being styles instead of style, no the value being assigned to the prop being this.styles().

I think it should be ```<div style={this.styles().model}>``` instead.
