### ISSUE TITLE
Remove react-addons-test-utils from peerDependencies

### ISSUE THREAD

**Issue by jharris4** [casesandberg/reactcss#111]
I keep getting this warning whenever I install any npm package:

`npm WARN reactcss@1.0.7 requires a peer of react-addons-test-utils@^0.14.8 || ^15.1.0 but none was installed.`

Can you remove the peer dependency on react-addons-test-utils please, it should only be in devDependencies, and *not* in peerDependencies...

**Comment by khakulov** [comment]
@casesandberg 
Please remove it from peerDependencies and add to devDependencies

**Comment by jharris4** [comment]
@khakulov It already is in devDependencies, so it really just needs to be removed from the peerDependencies

**Comment by jharris4** [comment]
@casesandberg I'd be happy to make a PR with the change to package.json, but I wasn't sure if there was some reason I'm not aware of that made you put it in peerDependencies... Can you clarify? Thx

**Comment by casesandberg** [comment]
I don't know how it snuck in there, would love a PR!

--
case

**Comment by casesandberg** [comment]
Fixed in https://github.com/casesandberg/reactcss/pull/113. In reactcss@1.0.8

**Comment by khakulov** [comment]
You did something wrong:

![image](https://cloud.githubusercontent.com/assets/441436/18749057/6a77f684-80d5-11e6-8c5b-3cac346d314d.png)

The warning still there

**Comment by jharris4** [comment]
Strange, the package.json on npm for 1.0.8 still has the peerDependency, but the package.json here on github does not. Not sure what happened...

**Comment by jharris4** [comment]
@casesandberg any idea why the change to package.json didn't make it to npm ?
