### ISSUE TITLE
Don't need vendor prefixes for widely supported CSS properties

### ISSUE THREAD

**Issue by andrewliebchen** [casesandberg/reactcss#12]
`box-shadow` and `border-radius` are already widely supported.

http://caniuse.com/#feat=border-radius
http://caniuse.com/#feat=css-boxshadow

If you're looking for more mixins to include out of the box (perhaps to showcase the library's features), check out [Bourbon](http://bourbon.io/docs/).

**Comment by 9o** [comment]
@andrewliebchen ***But what about Opera Mini?!***
