### ISSUE TITLE
Shared styles

### ISSUE THREAD

**Issue by henriquea** [casesandberg/reactcss#14]
Hey @casesandberg great work! 😀

I'm wondering wether this could be achieved in a better way having a built-in functionality or just sticking with this.

```es6
import {extend} from 'lodash';
import React from 'react';
import ReactCSS from 'reactcss';

class Foo extends ReactCSS.Component {

  sharedStyles() {
    return {
      container: {
        padding: '0.8em',
        fontSize: '1.2em'
      }
    };
  }

  classes() {
    let sharedStyles = this.sharedStyles();
    return {
      'default': {
        container: extend({}, sharedStyles.container, {
          width: '4em'
        }),
        actions: extend({}, sharedStyles.container, {
          width: '2em',
          textAlign: 'center'
        })
      }
    };
  }

}   
```
Thoughts?

cc @vladikoff

**Comment by casesandberg** [comment]
Hey @henriquea, sorry it took me a while to get back to you. 

There is actually a mixin called Extend that does the same thing!!

```
'default': {
   button: {
     height: '44px'
  },
  activeButton: {
     Extend: 'button',
     background: 'blue'
  }
}
```

It works to extend any style in the same class by name

**Comment by henriquea** [comment]
Hey @casesandberg yes I saw it today, totally lame! 😄 Then I closed the issue myself.

Having fun with this library man! Thanks for the good work

**Comment by casesandberg** [comment]
Awesome @henriquea, let me know any other thoughts or suggestions you have :)
