### ISSUE TITLE
Autoprefix returning empty list under webpack2

### ISSUE THREAD

**Issue by andrewgleave** [casesandberg/reactcss#141]
I traced through the code from `react-color` while looking at the https://github.com/casesandberg/react-color/issues/328 issue and I can see that everything is fine until https://github.com/casesandberg/reactcss/blob/master/src/autoprefix.js#L100

Looking at the transformed code, the `map` function that gets imported is lodash's specialised `arrayMap()` instead of `baseMap()` which is for mapping objects i.e.

    function arrayMap(array, iteratee) {
      var index = -1,
          length = array == null ? 0 : array.length,
          result = Array(length);

      while (++index < length) {
        result[index] = iteratee(array[index], index, array);
      }
      return result;
    }

So, this just returns `[undefined]` if the arg is an object.

I changed autoprefix to use plain JS as test case and it works as expected. See https://github.com/casesandberg/reactcss/compare/master...andrewgleave:master

Not sure what's going on and whether it's related to webpack2's tree shaking?

**Comment by andrewgleave** [comment]
Found it!

If you're using `lodash-webpack-plugin` you need to ensure you enable the `collections` feature.

If you don't, `map` will be specialised for arrays only.

**Comment by casesandberg** [comment]
Sorry about this. I updated ReactCSS to not use `map` on objects, you shouldn't have to do anything special using `react-color@2.11.2`
