### ISSUE TITLE
Add "styles" function to mixin

### ISSUE THREAD

**Issue by liady** [casesandberg/reactcss#16]
I think the `styles` function should be already included in `ReactCSS.mixin`, in order to avoid adding
```js
styles: function(){
  return this.css({})
},
```
in every React component.

**Comment by casesandberg** [comment]
@liady only problem is you can't declare it in your component if its already in the mixin and its necessary if you want to add arguments to it.

**Comment by liady** [comment]
@casesandberg Yeah, I see the problem.

Theoretically it could be:
```js
ReactCSS.mixin.styles = function(){
  return this.css(this.conditionalClasses && this.conditionalClasses.call(this));
}
```
and when using this mixin:
```js
var Item = React.createClass({
  mixins: [ReactCSS.mixin],
  // totaly optional now:
  conditionalClasses: function(){
    return {"hovered": this.state.hovered}
  }
```
And that way `conditionalClasses` will be an optional key only for those who want to declare conditional classes rules. All the rest won't have to declare `styles` at all.

But now it will probably be a breaking change for those who are already using it.

**Comment by casesandberg** [comment]
Yeah, but then the ES5 and ES6 versions are structured differently. I wanted to keep them as similar as possible until ES6 becomes the standard.
