### ISSUE TITLE
reactcss with bower.

### ISSUE THREAD

**Issue by piyushchauhan2011** [casesandberg/reactcss#17]
Is there any way so that we can use reactcss package with bower ?

The scenario is that we are using react-rails package and don't know how to integrate reactcss using npm ? We already have support for both bower and npm in the rails project and we can go for installing reactjs from npm but it will be redundant to do so as
```javascript
// Include the library
var React = require('react');
var ReactCSS = require('reactcss');
```
will include the react library too.

Currently `React` variable is exposed globally and we can use it directly. I just used only the second line i.e. `var ReactCSS = require('reactcss');`, but is that a good way ?

I'm just wondering what could possibly be right way of developing with `ReactCSS`

**Comment by piyushchauhan2011** [comment]
@casesandberg  ??

**Comment by casesandberg** [comment]
Looking into it today @piyushchauhan2011

**Comment by wdmtech** [comment]
Try: 
```BASH
bower install https://github.com/casesandberg/reactcss.git
```
In absence of a bower.json :smile:
