### ISSUE TITLE
What about media queries?

### ISSUE THREAD

**Issue by kevinsimper** [casesandberg/reactcss#20]
It looks really nice! But what about media queries? Of course I could just listen on window resize, but the semantic of media queries is also that you can nest them under the same selector like:

```
.myclass {
  @media(min-width: 1000px) {
    color: yellow;
  }
}
```

This makes it easier to make small css components that is responsive.

Is it possible to something like it in reactcss?

**Comment by casesandberg** [comment]
@kevinsimper ReactCSS will never support traditional media queries. I am currently working on another package that allows you to use element queries (width and height of each component) and that will be baked nicely into ReactCSS :)

**Comment by kevinsimper** [comment]
@casesandberg Okay nice, do you have a link? :)
