### ISSUE TITLE
ReactCSS 1.0.0

### ISSUE THREAD

**Issue by casesandberg** [casesandberg/reactcss#23]
With the release of React `0.14.0` and heavy usage of ReactCSS over the past few months I would like to propose some change for `1.0.0` and would love your feedback:

* Dropping the inheritance of `ReactCSS.Component` this was never meant to be long-term. `0.14.0` now throws warnings if you are not extending the original `React.Component`. 
* Add support for attaching multiple classes to elements. We can bake `react-map-styles` into ReactCSS and add a more robust string replace to allow for multiple classes + eval in the html. 
* Add in helper functions that can be used in loops for applying sudo-type classes re: first, last, nth-child, even, odd
* Heavy integration and support around using ReactCSS in React Native.

* Possibly remove the classes method and move everything unto the styles method with a function wrapping the return:

```
styles = () => {
  return {
    'default': {
      title: {
        color: '#333',
      },
    },
  };
}
```

And then you would pass the activations as a second parameter of the function:

    styles = () => {
        return css({
          'default': {
            title: {
              color: '#333',
            },
          },
        }, {
          'foo-bar': 2 + 2 === 4,
        });
      }

Or stick to the old methods with the caveat being the styles method will always have to be included even if you aren't passing custom activations in:

    classes() {
        return {
          'default': {
            title: {
              color: '#333',
            },
          },
        };
      }

    styles = () => css();

**Comment by casesandberg** [comment]
@9o @mhahn @seekshiva @liady @henriquea @shaunstanislaus @vladikoff @hharnisc

**Comment by hharnisc** [comment]
react-map-styles: :+1: 
React Native Support :+1: 

I also like the idea of removing the `classes` method in favor or using `styles`. I think it's more clear, though be good to think about a transitional period to allow people to migrate over to the new `styles`

What's the repercussions to dropping support for ReactCSS.Component inheritance?

**Comment by casesandberg** [comment]
@hharnisc Definitely not doing to drop support completely, however throw warnings to help people migrate. 

Only change with removing inheritance is that you will have to bind the styles method as with the fat arrow:
    
```
styles = () => css();
```

or in the constructor:

```
constructor() {
  super();
  this.styles = this.styles.bind(this);
}

styles() {
  return css();
}
```

**Comment by e-karma** [comment]
Hello @casesandberg, first off, i'd like to thank you for all the work you've put in for ReactCSS + Bounds.  I'm using both in my main project.  This is the first time i've enjoyed styling and don't think I can go back to the old way.   That said, I'm trying as hard as I can to stay with it, but it appears without .14 compatibility, I will need to migrate, at least in the short term.  

All your proposed changes seem like fantastic ideas and I was already thinking similar things.  Any idea when the updates might be available?  Thanks in advance and I look forward to supporting your work!

**Comment by casesandberg** [comment]
@e-karma Are you having problems with it in `0.14.0` ? The only issue I am aware of is it throws a console warning, but other than that is should work just fine.

**Comment by henriquea** [comment]
@casesandberg I like the proposal. Considering in  `0.14` the pure components/functions are a big deal, removing the old class method make sense for me.

**Comment by e-karma** [comment]
@casesandberg yea, every component that utilizes GetInitialState, it locks the page up.  Seeing many of these errors => 
-uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.0.0.0)
-uncaught TypeError: Cannot read property '_currentElement' of null
-Warning: getInitialState was defined on CreateEvent, a plain JavaScript class. This is only supported for classes created using React.createClass. Did you mean to define a state property instead?

i'm rather new to React so some of this may be my implementation, but after many hours wrestling with it, undoubtedly things break when using ReactCSS + Bounds and then clear up when removed. (doesnt' seem to like extending ReactCSS.component)

How long until you look to release an update?   Thanks again!

**Comment by mhahn** [comment]
+1 to the proposed changes, let me know if i can help!

**Comment by mhahn** [comment]
fyi: I'm getting these same errors "uncaught Error: Invariant Violation: findComponentRoot(..., .0.0.0.0.0)" when trying to use React 0.14. Initial load seems to work, but still publishes warnings, re-rendering seems to be failing at certain times.

**Comment by mhahn** [comment]
re: 
```
styles = () => {
    return css({
      'default': {
        title: {
          color: '#333',
        },
      },
    }, {
      'foo-bar': 2 + 2 === 4,
    });
  }
```

i'd be for simplifying to something like this. we don't use activations very often, but whenever we do i forget the syntax.

one comment is that i would prefer to limit the import boilerplate to setup a new component. if there was a way styles could look something like:

```
styles = () => {
    classes: {
         default: {
              ...
         }
    },
    activations: {
         ...
    },
}
```

where whatever was referencing styles in reactcss would do:

```
const { classes, activations } = Component.styles()
return css(classes, activations)
```

or something, then i wouldn't have to import `css` everywhere which would be nice.

**Comment by e-karma** [comment]
I know youre busy @casesandberg and definitley appreciate all the work you've done, but a timeline for 1.0 update would help immensely.

**Comment by casesandberg** [comment]
The plan is to have it done before the 18th of this month. Is there anything in particular you need in the mean time? I am working on a 1.0.0 branch and can build whatever you need next

**Comment by e-karma** [comment]
Hey, thanks!  Could you possibly swap out ReactCSS.Component for React.Component?  I had to remove the lib until fixed because that did more than generate a console warning.   What would the new implementation be?  ES7 Decorator for me is best-case as I have concerns with using mixins (they can only be used in React.createClass but not in React.Component ES6 class).  

-I'm eager for same update within react-bounds/context/color as Bounds became unusable since the update for the same reasons I think.
-Does ReactCSS enable :hover styling?

Thanks in advance; big fan of your work!!

**Comment by e-karma** [comment]
Hey @casesandberg, still on track for an update by tomorrow?

**Comment by casesandberg** [comment]
Sorry @e-karma, I have the week off and will be finished it up in the next few days

**Comment by mhahn** [comment]
@casesandberg lmk if there is anything i can help with, our team is focused on getting server side rendering released this week.

**Comment by e-karma** [comment]
Sounds good @casesandberg!  Happy thanksgiving and let me know if theres anything I can do to help

**Comment by igorpreston** [comment]
Hi @casesandberg, is this project still being maintained?

**Comment by casesandberg** [comment]
Yes @igorpreston, I have just been super busy the past couple of weeks. I will get something out as soon as I can!

**Comment by casesandberg** [comment]
Just got server-side rendering working (https://github.com/casesandberg/reactcss/commit/ca7cf3352b32fe74cc512643e2233381207ba02e), going to be upgrading the repo to work with `0.14.0` tonight!

**Comment by e-karma** [comment]
Excellent!  Thanks @casesandberg!  

I'm still curious, how are you going to include reactcss features into a react component? Inherit direcly from ReactCSS.Component, mixin or ES7 decorator?

Also when do you expect the 1.0.0 release w/ doc updates?

**Comment by igorpreston** [comment]
@casesandberg hello, may I know when 1.0.0 version will be released on npm with docs? Really looking forward to it.

**Comment by e-karma** [comment]
Hi @casesandberg, very confused at this point.  It seems it is still unfinished but you're last comment 2 weeks ago makes me unsure and unfortunately my project is stuck in limbo.  What is the status of the project?   Thanks

**Comment by 9o** [comment]
@e-karma Check https://github.com/casesandberg/reactcss/tree/1.0.0

**Comment by e-karma** [comment]
Thanks @9o and Thanks @casesandberg .   I spent some time with the new branch and have run into an unfortunate bug.  It appears as though ReactCSS cannot be used alongside other wrappers or ES7 decorators that are applied to the same class.

@Decorator
export class Klass extends Component { ... }
export default ReactCSS(Klass);

In that example, ReactCSS never works because it wraps the wrapper from Decorator and not the actual class. 

If this isn't error on my part, it seems like the only viable solution would be to rewrite reactcss wrapper either as decorator or as ES6 wrapper (ReactCSS(ClassName)).  Anyone else have insight or experience with this?

**Comment by e-karma** [comment]
Hey @casesandberg, any input on this?  Not sure which way to move forward. Thanks

**Comment by casesandberg** [comment]
Sorry. I am going to be releasing 0.5.0 with all of these changes this
weekend!

**Comment by casesandberg** [comment]
Ah @e-karma, I see what you are saying. I am going to do some digging to see if there is a way for this to work alongside decerators.

**Comment by e-karma** [comment]
@casesandberg Great! Let me know what you find out.

**Comment by e-karma** [comment]
Hey @casesandberg, did you have any luck?  If a fix has to wait at least until next week, thats no problem, just let me know so I can swap out the ES7 Decorators in the short-term.  As always, let me know if theres anything I can do to help!

**Comment by casesandberg** [comment]
Been looking into it but its really tricky. Wont have a fix in until mid-next-week at a minimum

**Comment by casesandberg** [comment]
Launched!
