### ISSUE TITLE
Server side rendering

### ISSUE THREAD

**Issue by mhahn** [casesandberg/reactcss#24]
I'm in the middle of converting to a universal app to support server side rendering and running into an issue where I need `react-map-styles` to run on the server side code.

Any ideas?

**Comment by casesandberg** [comment]
`react-map-styles` is just a string replace, you can just require it in and use the function to transform:

```
import 'mapStyles' from 'react-map-styles';

let output = ReactDOMServer.renderToString(RootComponent);
let transformed = mapStyles(output);
```

**Comment by mhahn** [comment]
:heart_eyes:

**Comment by mhahn** [comment]
hm, i don't think this is as straightforward as that. i think the `is` is somehow preventing react from processing the jsx tag completely.

before the transformation, `renderToString` outputs:
```
<div className="infoBar___yu82e well" is="root" children="[object Object]" data-reactid=".2cfeu6dc35s.3">
```

after the transformation, we get:
```
<div className="infoBar___yu82e well" style={ this.styles().root } children="[object Object]" data-reactid=".2cfeu6dc35s.3">
```

so it is correctly expanding `is`, but `className` isn't getting converted and neither is children.

i'm testing this with this repo: https://github.com/erikras/react-redux-universal-hot-example

with the following diff:

```
diff --git a/src/components/InfoBar/InfoBar.js b/src/components/InfoBar/InfoBar.js
index adecf18..7b68d62 100755
--- a/src/components/InfoBar/InfoBar.js
+++ b/src/components/InfoBar/InfoBar.js
@@ -1,7 +1,8 @@
-import React, {Component, PropTypes} from 'react';
+import React, {PropTypes} from 'react';
 import {bindActionCreators} from 'redux';
 import {connect} from 'react-redux';
 import {load} from 'redux/modules/info';
+import { Component } from 'reactcss';

 @connect(
     state => ({info: state.info.data}),
@@ -12,11 +13,21 @@ export default class InfoBar extends Component {
     load: PropTypes.func.isRequired
   }

+  classes() {
+      return {
+          default: {
+              root: {
+                  backgroundColor: 'black',
+              },
+          },
+      };
+  }
+
   render() {
     const {info, load} = this.props; // eslint-disable-line no-shadow
     const styles = require('./InfoBar.scss');
     return (
-      <div className={styles.infoBar + ' well'}>
+      <div className={styles.infoBar + ' well'} is="root">
         <div className="container">
           This is an info bar
           {' '}
diff --git a/src/server.js b/src/server.js
index 5eee239..09ae331 100755
--- a/src/server.js
+++ b/src/server.js
@@ -12,6 +12,7 @@ import Html from './helpers/Html';
 import PrettyError from 'pretty-error';
 import http from 'http';
 import SocketIo from 'socket.io';
+import mapStyles from 'react-map-styles';

 import {ReduxRouter} from 'redux-router';
 import createHistory from 'history/lib/createMemoryHistory';
@@ -101,8 +102,11 @@ app.use((req, res) => {
         if (status) {
           res.status(status);
         }
-        res.send('<!doctype html>\n' +
-          ReactDOM.renderToString(<Html assets={webpackIsomorphicTools.assets()} component={component} store={store}/>));
+        const content = ReactDOM.renderToString(<Html assets={webpackIsomorphicTools.assets()} component={component} store={store}/>);
+        const transformed = mapStyles(content);
+        console.log(content);
+        console.log('TRANSFORMED:\n' + transformed);
+        res.send('<!doctype html>\n' + transformed);
       }).catch((err) => {
         console.error('DATA FETCHING ERROR:', pretty.render(err));
         res.status(500);
diff --git a/webpack/dev.config.js b/webpack/dev.config.js
index 132862b..24b25e2 100755
--- a/webpack/dev.config.js
+++ b/webpack/dev.config.js
@@ -62,7 +62,7 @@ module.exports = {
   },
   module: {
     loaders: [
-      { test: /\.js$/, exclude: /node_modules/, loaders: ['babel?' + JSON.stringify(babelLoaderQuery), 'eslint-loader']},
+      { test: /\.js$/, exclude: /node_modules/, loaders: ['babel?' + JSON.stringify(babelLoaderQuery), 'eslint-loader', 'react-map-styles']},
       { test: /\.json$/, loader: 'json-loader' },
       { test: /\.less$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!less?outputStyle=expanded&sourceMap' },
       { test: /\.scss$/, loader: 'style!css?modules&importLoaders=2&sourceMap&localIdentName=[local]___[hash:base64:5]!autoprefixer?browsers=last 2 version!sass?outputStyle=expanded&sourceMap' },
```

**Comment by casesandberg** [comment]
What do you mean by "className isn't getting converted and neither is children"?

**Comment by mhahn** [comment]
the output from `renderToString` is:

```<div className="infoBar___yu82e well" style={ this.styles().root } children="[object Object]" data-reactid=".2cfeu6dc35s.3">```

as opposed to:

```<div class="infoBar___yu82e well" data-reactid=".2cfeu6dc35s.3">```

without reactcss.

**Comment by mhahn** [comment]
it's not converting `className` to `class`

**Comment by mhahn** [comment]
a more straight forward repro (assuming react and react-dom):

repro.js
```
var React = require('react');
var ReactDOM = require('react-dom/server');

var CommentBox = React.createClass({displayName: 'CommentBox', render: function() { return ( React.createElement('div', {className: "commentBox"}, "Hello, world! I am a CommentBox.")); } });
var CommentBoxWithIs = React.createClass({displayName: 'CommentBox', render: function() { return ( React.createElement('div', {className: "commentBox", is: "test"}, "Hello, world! I am a CommentBox.")); } });
var commentBox = React.createElement(CommentBox, null);
var commentBoxWithIs = React.createElement(CommentBoxWithIs, null);

console.log('original: %s', ReactDOM.renderToString(commentBox))
console.log('with reactcss: %s', ReactDOM.renderToString(commentBoxWithIs))
```

results in:

```
$ node repro.js
original: <div class="commentBox" data-reactid=".1ukajf9nxts" data-react-checksum="-1784209694">Hello, world! I am a CommentBox.</div>
with reactcss: <div className="commentBox" is="test" children="Hello, world! I am a CommentBox." data-reactid=".adjpxx9ji8" data-react-checksum="-1799212608">Hello, world! I am a CommentBox.</div>
```

**Comment by mhahn** [comment]
it has to do with `is` explicity:

https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js#L745
https://github.com/facebook/react/blob/master/src/renderers/dom/shared/ReactDOMComponent.js#L491

if `is` is listed in the props at all, it treats all the attributes within the element as "custom", which means it just dumps the `key="value"`, which is why `className`, `children` etc. don't get converted.

if you read through the React 0.14 release notes you can see them mention this:
http://facebook.github.io/react/blog/2015/09/10/react-v0.14-rc1.html#notable-enhancements

"In React DOM, arbitrary attributes are supported on custom elements (those with a hyphen in the tag name or an is="..." attribute)"

aside from coming up with an alias for `is` i can't think of a way to make this work.

**Comment by casesandberg** [comment]
Well shit. Thanks for digging into this. I am going to dig into this tonight to see if there is a quick fix, but I agree we might just have to move away from `is`. Do you have any thoughts around what we could change it to?

**Comment by mhahn** [comment]
I'm not sure what the alternative should be, "is" really does make the most sense.

I think react has conflicting handling of "is", on one hand its listed as a valid html dom property, on the other hand, using it means the component is considered custom...

i filed this issue: https://github.com/facebook/react/issues/5298

but i'm not too confident that will get resolved/resolved quickly.

some ideas on alternatives:

- using a vendor suffix: `isCSS="root"`, looks ugly though
- since you mentioned including multiple classes in https://github.com/casesandberg/reactcss/issues/23 (which i think would be great): `classes="common root"`
the above also stays consistent with the `classes` function, which i kind of like.

**Comment by casesandberg** [comment]
Sorry for the delay on this @mhahn I am going to try and get a solution working for you tonight. 

How would you feel about using spreads instead of static properties? That way this can all be done programmatically and not have to rely on a string replace:
```
<div {...class('foo bar')} />
```

**Comment by mhahn** [comment]
no worries, don't feel like you have to rush on my account. i'm happy to wait for the 1.0 release.

thinking through the case where i would also be spreading other properties:

```
<div
    className="something"
    otherProp="something"
    {
         ...class("foo bar")
         ...this.props
    }
/>
```

i'm ok with that, i think the static property looks better, but i would be willing to give that up for the simplicity of not having to do something special for server-side rendering.

**Comment by casesandberg** [comment]
Another solution would be revert back to the string replace but use `class` instead of `is`. I wonder if this is possible (I am pretty sure react will just throw a warning). Because reverting back to the original syntax would be nice too. This might get confusing mixing `class` and `className` though.

**Comment by mhahn** [comment]
i like the idea of supporting the function as well as the static property.

i think using `class` would be too confusing. `inlineClass` or `classes` would work for me. i like the plural version because it indicates that you can use multiple values.

**Comment by mhahn** [comment]
i tried switching this to `inlineStyles` to see if i could then run `mapStyles` on the React rendered output. From what I can tell, react drops any properties that it can't handle and don't start with `data-`. So I'm opting for not relying on react-map-styles and just going with the vanilla `style=`

**Comment by mhahn** [comment]
even if we used something like `data-inline-styles`, we use the material-ui library which relies on child components pulling the style from parent components in some cases. as soon as react renders those elements, it doesn't matter if we replace `data-inline-styles` since the child components have already been rendered.

**Comment by casesandberg** [comment]
Hey, just got server-side rendering working in the `1.0.0` branch!

https://github.com/casesandberg/reactcss/commit/ca7cf3352b32fe74cc512643e2233381207ba02e

It's a little messy now, I will clean it up tonight and write a paragraph on how to use it so you can get running with it before the official 1.0.0 launch

**Comment by mhahn** [comment]
i'd love to bench mark this and get a a sense if it has any performance implications. iterating through the whole tree before rendering seems somewhat intense to me vs just not using `is`

**Comment by casesandberg** [comment]
Yeah definitely, this isn't intended to run client-side in prod. I would say you would still want to do a string replace when building for prod. Similarly you would use this method server-side for serving up static assets.

**Comment by mhahn** [comment]
yea, the issue with the string replace is libraries like
http://www.material-ui.com/#/ where they fetch the style/attributes from
the parents.

so if react renders the components, we lose out on passing those values
down.

**Comment by casesandberg** [comment]
What do you mean by that?

**Comment by mhahn** [comment]
if we do something like:

class Parent extends Component {
      classes() {
          "Parent": {
               "primaryTextColor": "blue",
          }
     }
     render() {
         return <Child is="Parent" />;
     }
}

where Child is something like:

class Child extends Component {
      render() {
            const { primaryTextColor } = this.props;
            return <SubComponent primaryTextColor={primaryTextColor} />;
      }
}

my understanding is that as soon as we call ReactDOM.renderToString() we
need to have "primaryTextColor" passed down to the SubComponent. the string
replace doesn't achieve that right?

**Comment by casesandberg** [comment]
Ah, it totally does because it changes the render on parent to be a spread and passes it down as a spread:

before:
    render() {
         return <Child is="Parent" />;
     }

After:

   render() {
         return <Child {...this.styles().Parent} />;
     }

**Comment by mhahn** [comment]
sorry, "it totally does" -- need to be there right? or the string replace handles that?

**Comment by casesandberg** [comment]
Yep, the string replace will transform it correctly. Similarly the solution that iterates through all the children will transform it the same if you try to render it with ReactDOMServer!

**Comment by mhahn** [comment]
Ok, I'm with you.

String replace over the files works, it doesn't work if you call it after the `ReactDOM.renderToString` (which was the initial idea for server side rendering).

The solution you have for iterating through the children does look like it solves the issue, I'd just be interested in exploring what overhead this adds to each request for server side rendering.

overall, thanks so much for getting to this!

**Comment by casesandberg** [comment]
Did you ever do some testing to see if this solution adds to much overhead?

**Comment by mhahn** [comment]
I didn't, I just am about to get server side rendering deployed in the next
couple of days. Once that is there I'll have a baseline to test this.

I removed "is=" from all of my components, but we should be able to see if
simply iterating through the tree has any noticeable impact.

**Comment by casesandberg** [comment]
Ah! `reactcss@1.0.0` removes react-map-styles and works flawlessly with server side rendering!
