### ISSUE TITLE
core: Add syntactic sugar when extending a component

### ISSUE THREAD

**Issue by suitupalex** [casesandberg/reactcss#27]
Say I've got a ReactCSS component called `Page`:

```js
class Page extends ReactCSS.Component {
  classes() {
    return {
      'default': {
        'page': {
          fontFamily: 'Arial'
        , color: '#f00'
        }
      }
    }
  }
}
```

Now I'd like to make a subclass of `Page` called `BoldPage`. Right now to reuse the classes, I'd have to do something like:

```js
const merge = require('merge')

class BoldPage extends Page {
  classes() {
    return merge.recursive(true, super.classes(), {
      'default': {
        'page': {
          fontWeight: 'bold'
        }
      }
    })
  }
}
```

I'm proposing a bit of syntactic sugar built into the module since this (in my opinion) would be a common pattern:

```js
class BoldPage extends Page {
  classes() {
    return ReactCSS.extendSuper(super, {
       ...
    })
  }
}
```

Good idea? Bad idea?

If it sounds like a good idea, I wouldn't mind tackling the PR for it.

**Comment by casesandberg** [comment]
Hmm, why do you find yourself extending components in that way? I dont know what you are trying to do.
