### ISSUE TITLE
Use modularized lodash

### ISSUE THREAD

**Issue by abhishiv** [casesandberg/reactcss#28]
Currently, entire lodash is being included in some places

https://github.com/casesandberg/reactcss/search?utf8=%E2%9C%93&q=lodash

In my case it's a problem because including reactcss adds around 450k because of lodash.

**Comment by casesandberg** [comment]
I will fix this today!

**Comment by casesandberg** [comment]
Fixed! Update to `reactcss@0.4.3` to reap the leaner codebase!

**Comment by abhishiv** [comment]
Awesome thank!
