### ISSUE TITLE
Redux Compatibility? 

### ISSUE THREAD

**Issue by e-karma** [casesandberg/reactcss#36]
Hello Again! 

Can ReactCSS be used with a Redux Architecture?  I imagine you're familiar, but we have separated components into Container (that pass data to presentational and are generated by redux) and Presentational components (pure markup). 

Can we use ReactCSS in presentational components, considering they are function, not a class?  Worth noting is we can't wrap presentational components into a wrapper class.

Presentational component example:
const Example = () => (
<div></div>
);

If Redux + ReactCSS aren't a good fit, not a big problem, but as you know i'm trying my hardest to keep RCSS involved! Thanks again and I hope all is well!

**Comment by casesandberg** [comment]
Hey @e-karma! Thinking through this now. It needs to be something that works with presentational classes as well. This is something I am going to solve quickly because I really do want support with Redux.

Also, why is it that you cant wrap presentational components in a wrapper class? ie: 
```
const Example = () => (

)

export default ReactCSS(Example)
```

**Comment by e-karma** [comment]
Our presentational components are already wrapped with redux container components. I am not sure they work well with reactcss, considering history with decorators support. Even though we can wrap presentational component with reactcss, that's not wrapped with redux container, we still have no place to put the classes() function, because presentational component is function itself.

Decorator Support enables wrapping of the Presentation Component with ReactCSS and still use Redux Container, but the main problem remains, which is how to access classes() that is attached only to a class.

If the presentational component wasn't wrapped, it could work fine, but again, we have no place to put classes() function because component is not a class.  

Do you have any ideas?

Thanks again!

**Comment by casesandberg** [comment]
@e-karma Sorry for the delay. Been brainstorming all day and have a simplified API for the `1.0.0` release which has support for react-native, server side rendering and and redux. Coming in the next few days!

**Comment by casesandberg** [comment]
@e-karma `reactcss@1.0.0` hit today with support for redux! Check out more about it here: http://reactcss.com/#redux
