### ISSUE TITLE
Documentation site looks odd in Firefox vs Chrome

### ISSUE THREAD

**Issue by muffinresearch** [casesandberg/reactcss#5]
Chrome (43.0.2357.130): 

![documentation___reactcss](https://cloud.githubusercontent.com/assets/1514/8502690/e5206fe0-21ab-11e5-8345-6ff25c686789.png)

Firefox: 39.0

![documentation___reactcss](https://cloud.githubusercontent.com/assets/1514/8502698/0d1c7098-21ac-11e5-9198-5ebc900a0f1e.png)

**Comment by casesandberg** [comment]
Thats no good! I went ahead and fixed that @muffinresearch, thanks for the heads up!

https://github.com/casesandberg/reactcss/commit/4eb5826357c02cb920c908c2a7de32ae87abf281
