### ISSUE TITLE
Hover.js > hover.js

### ISSUE THREAD

**Issue by jaunkst** [casesandberg/reactcss#60]
Case sensitive import.

Module not found: Error: Cannot resolve 'file' or 'directory' ./components/hover.js in /home/jaunkst/Git/bitmonolith/lookout-ui/node_modules/reactcss/lib

**Comment by BlockNinja** [comment]
I'm guessing the author uses a OSX or Windows, as this is only an issue on Linux (you know, that platform that runs most webservers?)

Renaming to hover.js fixes this problem.
