### ISSUE TITLE
ReactCSSTransitionGroup example

### ISSUE THREAD

**Issue by raulanatol** [casesandberg/reactcss#61]
reactcss is compatible with ReactCSSTransitionGroup? Any examples?

**Comment by casesandberg** [comment]
Oh! I am not sure, I will try and look into this soon

**Comment by kuailingmin** [comment]
const styles = ReactCss({
            'default':{
                head : {
                    position:'absolute',
                    top:'0px',
                    left:'0px'
                }
            }
        });
<div style={styles.head}>

**<div style={styles.head,styles.headOne}>**
but:I want to add more style CSS attributes,How to write?

**Comment by kuailingmin** [comment]
`<div style={styles. head}></div>`

**Comment by casesandberg** [comment]
I am not sure what you are asking? @kuailingmin

**Comment by casesandberg** [comment]
Looked into this today and it looks like there is no way to do inline styles with CSS Transition Group /: https://facebook.github.io/react/docs/animation.html
