### ISSUE TITLE
Is Hover broken?

### ISSUE THREAD

**Issue by Spiralis** [casesandberg/reactcss#63]
I have tried to follow the example on http://reactcss.com/#hover, but I am unable to make it work. It doesn't seem to recalculate the styles. 

I used the default example from the website at http://reactcss.com/#hover.

**Comment by faroe228** [comment]
It's not working for me and I'm using React.version 15.1.0
I noticed it's using a boolean hover property.  My first workaround was to just dynamically assign the default css based on the hover property value ( looks like hover key is ignored ).

**Comment by rkumar-cognam** [comment]
not working for me too.  Where exactly you put
{
'hover': (props.hover === true)
}
can you please paste your code

**Comment by vinceroti** [comment]
If anyone comes across this and still is having trouble with hover, you have to add this.props to the end of your styles. I'll post my code as an example.
`import reactCSS, { hover } from 'reactcss';
import React, { Component } from 'react';
import { Glyphicon } from 'react-bootstrap';




class Portfolio extends Component {

  render() {
    const styles = reactCSS({
      'default': {
        portfolio: {
          backgroundColor: 'gray',
          color: 'white',
          margin: 'auto',
          textAlign: 'center',
          paddingTop: '50px'
        },

        line: {
          padding: '0',
          border: 'none',
          borderTop: 'solid 5px',
          textAlign: 'center',
          width: '100px',
          maxWidth: '20%',
          margin: 'auto',
          backgroundColor: '#18BC9C',
          color: 'white',
          display: 'inline-block',
          borderRadius: '250px',

        },

        star: {
          display: 'inline-block',
          position: 'relative',
          top: '11px',
          fontSize: '2em',
          padding: '0 0.25em',
          borderColor: 'white',
        },

        title: {
          fontWeight: 'bold',
          fontSize: '40px',
          letterSpacing: '2.5px'
        },

        ul: {
          paddingLeft: '0',
          listStyleType: 'none'
        },
        image: {
          display: 'inline-block',
          margin: 'auto',
          marginTop: '20px',
          width: '250px',
          maxWidth: '90%',
        },
      },
      'hover': {
        image: {
          backgroundColor: "red"
        }
      }
    }, this.props)

    return (
      <div style={styles.portfolio} id="portfolio">
        <h2 style={styles.title}> PORTFOLIO </h2>
        <hr style={styles.line}/>
          <Glyphicon glyph="star" style={styles.star} />
        <hr style={styles.line} />
        <div>
          <ul style={styles.ul}>

              <li style={styles.image}><img style={styles.image} src="wiki.png" alt="Wikipedia Logo" /></li>

              <li style={styles.image}><img style={styles.image}  src="google.png" alt="Google Logo" /></li>
            </ul>
        </div>
      </div>
    );
  }
}



export default hover(Portfolio)
`
