### ISSUE TITLE
Why is there an example titled Redux?

### ISSUE THREAD

**Issue by 0x80** [casesandberg/reactcss#70]
It is an example of a functional stateless component but that has nothing to do with Redux. To me this is only confusing.

Similarly the example of React Native has nothing specific to RN so isn't it enough to just mention it's compatible with RN? Now you just waste time trying to find the differences between the examples only to find out that they're the same.

**Comment by casesandberg** [comment]
Sorry for the confusion, I will update the titles so they are less confusing :)
