### ISSUE TITLE
Pseudo-classes are not pseudo-elements (documentation nitpick)

### ISSUE THREAD

**Issue by papermana** [casesandberg/reactcss#71]
The website mentions [pseudo-elements](https://developer.mozilla.org/en/docs/Web/CSS/Pseudo-elements), however the examples are all [pseudo-classes](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-classes). Additionally, there exist all sorts of pseudo-classes, but it seems that in that section only order/position pseudo-classes are relevant. I don't really know what to call this specific kind of pseudo-classes; maybe simply listing all the possible ones would make the text clearer?

Just some nitpicks before even using the module (though it looks interesting).

**Comment by casesandberg** [comment]
Ah, great point!
