### ISSUE TITLE
Remove lodash as a dependency and use lodash 4.0 submodules as needed

### ISSUE THREAD

**Issue by danfernand** [casesandberg/reactcss#76]
For package footprint considerations can we please remove lodash 3 and replace where its needed with lodash submodules. 

This will prevent the whole library to get sucked into a bundle and would be at par with everyone else that is at lodash 4.0 submodules.

Thanks!

**Comment by casesandberg** [comment]
This is in `reactcss@1.0.5`

**Comment by lstkz** [comment]
@casesandberg 
This is still not fixed, and the whole library is loaded.
Screen from webpack bundler analyzer:

![image](https://user-images.githubusercontent.com/4478684/41168617-c8409e26-6b46-11e8-90d3-efe18b7a0870.png)
