### ISSUE TITLE
Input Placeholder Color

### ISSUE THREAD

**Issue by derekjobst** [casesandberg/reactcss#78]
I'm having trouble setting the placeholder color using `reactcss`. Autoprefixer appears to support it (for auto expansion), but I'm not sure it is compatible with the way this module works. I've attempted the following solutions:

### Peseudo-selector Style:
```json
'default: { ... },      
placeholder: {
  input: {
    color: 'red'
  }
}, ...
```

### Perhaps a separate selector:
```json
'default: {
  input: {
    placeholderColor: 'red' 
  },      
}, ...
```

Please advise.

**Comment by casesandberg** [comment]
I may be wrong but I dont think there is a way of doing that with inline styles?
