### ISSUE TITLE
Write type declaration file for typescript

### ISSUE THREAD

**Issue by alex3165** [casesandberg/reactcss#98]
Any plan to write the type declaration file of the library for typescript ?

And  maybe push it to https://github.com/DefinitelyTyped/DefinitelyTyped as well ?

**Comment by casesandberg** [comment]
Yeah! Hopefully I can get to it one day soon

**Comment by casesandberg** [comment]
@chrisgervang think you could tackle this?

**Comment by casesandberg** [comment]
Someone just made one! https://www.nuget.org/packages/reactcss.TypeScript.DefinitelyTyped/0.0.1
